name: Automated Greetings

on:
  [pull_request_target, issues]

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello @${{ github.actor }},

            Thank you for creating an issue. Your effort in improving this project is greatly appreciated. Our team will review your submission promptly and provide feedback or updates as necessary. 

            Best regards,  
            FED Team
          pr-message: |
            Hello @${{ github.actor }},

            Thank you for your contribution to this project. Your pull request has been submitted successfully. A maintainer will review it at the earliest opportunity and provide feedback or approval.

            Your support is invaluable in making this project better.

            Best regards,  
            FED Team
